Add support of `yiisoft/translator` version `^3.0`
yiisoft/translator-message-db pull request #66
Opened 2024-01-30 20:59 UTC by thenotsoft

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | -

2024-01-30 21:15 UTC, terabytesoftw approved these changes

2024-01-31 06:48 UTC, vjik requested changes
It's good. All that remains is to add a line to changelog.

2024-01-31 07:47 UTC, vjik commented on CHANGELOG.md
> +- Enh #66: Add support of yiisoft/translator version ^3.0 (@thenotsoft)
```suggestion
- Enh #66: Add support of `yiisoft/translator` version `^3.0` (@thenotsoft)
```

2024-01-31 07:47 UTC, vjik approved these changes

2024-01-31 07:47 UTC, merged